In [1]:
import numpy as np

Создать массив со случайными значениями и максимальный элемент заменить на 0

In [2]:
random_array = np.random.rand(3, 3)

print("Исходный массив:")
print(random_array)

max_value = np.max(random_array)
max_indices = np.where(random_array == max_value)
random_array[max_indices] = 0

print("\nМассив с замененным максимальным элементом на 0:")
print(random_array)

Исходный массив:
[[0.25959588 0.30997672 0.09656198]
 [0.39961561 0.82219361 0.70885044]
 [0.32173713 0.89784642 0.08931853]]

Массив с замененным максимальным элементом на 0:
[[0.25959588 0.30997672 0.09656198]
 [0.39961561 0.82219361 0.70885044]
 [0.32173713 0.         0.08931853]]


Создать матрицу 3x3 со значениями от 0 до 8

In [3]:
matrix = np.arange(9).reshape(3, 3)

print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Используя numpy создать и нормализовать матрицу.

In [4]:
def normalize_matrix(matrix):
  return (matrix - np.min(matrix)) / (np.max(matrix) - np.min(matrix))

In [5]:
print(normalize_matrix(matrix))

[[0.    0.125 0.25 ]
 [0.375 0.5   0.625]
 [0.75  0.875 1.   ]]
